### ISSUE TITLE
JAVA_HOME

### ISSUE THREAD

**Issue by ColtonIdle** [mdogan/homebrew-zulu#16]
This might be a dumb question, but does this install to the typical java location so that JAVA_HOME is set automatically, or are there any instructions on how to set java_home when installing from homebrew-zulu?

**Comment by mdogan** [comment]
Yes, this formula uses the installer `.pkg` provided by Azul, which installs into standard `/Library/Java/JavaVirtualMachines/` directory. But still you might need to explicitly define `JAVA_HOME` in your shell profile. So using `/usr/libexec/java_home` tool:

Bash:
```bash
export JAVA_HOME=$(/usr/libexec/java_home)
```

Fish:
```fish
set -x JAVA_HOME (/usr/libexec/java_home)
```

**Comment by ColtonIdle** [comment]
Thanks for the response. JAVA_HOME and java_home still make my head hurt after all these years and your explanation really helped. Much appreciated @mdogan !
