### ISSUE TITLE
Zulu JDK 14

### ISSUE THREAD

**Issue by oranheim** [mdogan/homebrew-zulu#2]
Hi,

Can you jdk 14?

https://www.azul.com/downloads/zulu-community/?version=java-14&architecture=x86-64-bit&package=jdk

Cheers
Ove

**Comment by mdogan** [comment]
Thanks for the notice.

Closed by https://github.com/mdogan/homebrew-zulu/commit/a193f86864b254921b56bb71895ddeca2fd4f089
