### ISSUE TITLE
`JAVA_HOME` value?

### ISSUE THREAD

**Issue by skwh** [mdogan/homebrew-zulu#38]
Hi, I am using the zulu-jdk8 cask on my M1 Mac. After I install I am able to see that this version is being used with `java -version` but I am not sure what the value for the `JAVA_HOME` variable should be. I am not seeing anything in the locations of similar installs like OpenJDK8. Would you be able to advise me on what the `JAVA_HOME` value should be when using these packages? Thank you.

**Comment by JakeWharton** [comment]
If you just want what is the default then you can use the return value from `/usr/libexec/java_home`.

I use this in conjunction with a function to change the JDK on demand:
```bash
# Java
jdk() {
  version=$1
  export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
  java -version
}
# Expose the default Java so tooling relying on the env var can pick up on it.
export JAVA_HOME=$(/usr/libexec/java_home)
```

**Comment by skwh** [comment]
Thank you!!
