### ISSUE TITLE
GitHub App token used for CI needs 'workflows' permission

### ISSUE THREAD

**Issue by JakeWharton** [mdogan/homebrew-zulu#46]
It's new and is required in order to create a new workflow as part of the action.

See https://github.com/mdogan/homebrew-zulu/actions/runs/4482449704

**Comment by mdogan** [comment]
I'll fix it, sure.

**Comment by mdogan** [comment]
Fixed by https://github.com/mdogan/homebrew-zulu/commit/03883d6a80af14f1fb050e2db529a33b91962560
