### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by shatyuka** [mdogan/homebrew-zulu#6]
I don't know whether homebrew supports Apple Silicon well currently. However zulu released the aarch64 build for macOS few days ago.

https://cdn.azul.com/zulu/bin/zulu8.50.0.1013-ca-jdk8.0.275-macos_aarch64.dmg
https://cdn.azul.com/zulu/bin/zulu11.43.1007-ca-jdk11.0.9.1-macos-aarch64.dmg
https://cdn.azul.com/zulu/bin/zulu13.35.1009-ca-jdk13.0.5.1-macos-aarch64.dmg

Looking forward to that.😊

**Comment by mdogan** [comment]
There's a pending PR for adding `aarch64`: https://github.com/mdogan/homebrew-zulu/pull/7. I don't have access to new Apple silicon macs to verify and it seems Github workflow doesn't support them yet. 🤞🏼

**Comment by mdogan** [comment]
Fixed by https://github.com/mdogan/homebrew-zulu/commit/f35b31e54c4e4c644d4a3ea480056833d88aac73
