### ISSUE TITLE
brew cask installation error 

### ISSUE THREAD

**Issue by mark-baumann** [mdogan/homebrew-zulu#8]
Hi, 

if I want to brew install zulu java, there comes following error message:

<img width="568" alt="Bildschirmfoto 2020-12-21 um 13 45 24" src="https://user-images.githubusercontent.com/60445235/102778584-20887780-4393-11eb-830d-438d89c0d220.png">

...but Cask is already successfully installed:
<img width="430" alt="Bildschirmfoto 2020-12-21 um 13 43 40" src="https://user-images.githubusercontent.com/60445235/102778634-3bf38280-4393-11eb-8674-1aca6b404515.png">

I also reinstalled cask.

Does anyone know what I can do? 
My user has the rights to install it. Su is not allowed from brew.

**Comment by mdogan** [comment]
That's because of a new change in Homebrew. `brew cask <command>` is deprecated. You should use `brew <command> --cask` from now on. So instead of `brew cask install zulu-jdk8`, you should write `brew install --cask zulu-jdk8`.

**Comment by mark-baumann** [comment]
Thank you for the answear Mehmet!
